### ISSUE TITLE
Loading of jquery 1.11.2 results in undefined

### ISSUE THREAD

**Issue by arjenvdhave** [mendix/AppStoreWidgetBoilerplate#14]
In the boilerplate code of the widget a specific version of jquery (1.11.2) is loaded as a module like so:

'WidgetName/lib/jquery-1.11.2.min'
It is then mapped to the variable _jQuery

When you look in the Chrome debug tool Network tab you can see that the jquery 1.11.2 js is actually loaded however the _jQuery remains undefined.

The line "var $ = jQuery.noConflict(true);" therefore is just using the global scope jquery since it is using the var jQuery instead of _jQuery.

Does this mean there is not way of loading external javascript files into your widget when you are using only a define?
I know the require method has the ability of specifying packages, however the define doesn't.

**Comment by Achiel** [comment]
I have an open PR: https://github.com/mendix/AppStoreWidgetBoilerplate/pull/13 that should solve this :)

**Comment by arjenvdhave** [comment]
It would solve the jquery problem :)
However i would like to know how to load external javascript files.

An example is found in the calendar widget.
Which relies on fullcalender.io and moment.js.

is i load them in define using "WidgetName/lib/moment.min" they remain undefined.
Even tough i do see they get loaded when monitoring the network tab in chrome debug tools.

**Comment by Achiel** [comment]
Are the external javascript files that you want to load AMD-compliant?

**Comment by arjenvdhave** [comment]
They should be.
I was prototyping with fullcalander.io and moment.js.
As far as i can see they are both AMD compliant.

**Comment by Achiel** [comment]
If they're AMD-compliant then they should be loaded via define... That's the whole point :)

 Do you have some code snippets? I guess the first couple of lines of the libs you're loading and where you're depending on them?

**Comment by Achiel** [comment]
aaah I think I see what you mean. in https://github.com/mendix/Calendar/blob/master/src/calendar/widget/calendar.js#L19 we work around situations like that by using some configuration in the require... 

However, I personally prefer using explicit paths and depending on those. But that would also require (pun intended) you to edit your libraries...

**Comment by arjenvdhave** [comment]
Yep that's what i was aiming at.
So when using external libs you cant only use define.

I tested it by using only momentJs and this works with the:
'WidgetName/lib/moment.min'

The "fun" thing is.
When i also add the fullcalendar lib i get an error.
Since the full fullcalendar it selfs also relies on the module "moment"

but since im not loading the moment lib with the module name "moment" but with 'WidgetName/lib/moment.min' i get an error that the module moment can not be loaded :(

I think i will switch back to using require instead of define for this widget :)

**Comment by Achiel** [comment]
That's what I was referring to when I said:
"However, I personally prefer using explicit paths and depending on those. But that would also require (pun intended) you to edit your libraries..."

You'd actually have to change the fullcalendar.js file to depend on "WidgetName/lib/moment.min" ....

**Comment by RoelandSalij** [comment]
Exactly, that or modifying the libraries of fullcalendar so they are using explicit paths like Achiel mentioned. I was also wrestling with this issue, and stayed with the 'configuration in require' solution in the end.

**Comment by Achiel** [comment]
The reason you shouldn't use require is that you can run into all sorts of other collisions if other library developers choose to load their own libraries that are *also* called moment, or in situations where you load the code asynchronously, such as mobile... 

If you can work around it I highly recommend using define over require.

**Comment by arjenvdhave** [comment]
Ok, thanks guys.
It makes more sence now why i couldn't get my prototype to work.

Don't like the solution yet, since i would like to use define and not change the code of my external libs :)

I hope this is something can be fixed in a later version?
Or is this something which should change in Dojo rather than this boilerplate?

**Comment by Achiel** [comment]
It's something we're looking at, we don't really like the current situation either.
