### ISSUE TITLE
non-persistant entities

### ISSUE THREAD

**Issue by WillemUXMendix** [mendix/AppStoreWidgetBoilerplate#16]
although the test project is build with a non-persistant entity as a testcase: a widget created with the boilerplate which actually passes an entity to the widget is never allowed to use a non-persistant entity.
Even when adding allowNonPersistableEntities="true" to the entity in the XML.

This is either a bug or the test project needs to be updated to only use a persistant object. At the moment it's not possible to use the test project to test a widget which uses a entity as input.

**Comment by JelteMX** [comment]
We will look into this for #31
