### ISSUE TITLE
IE8 non compatibility (easily fixed)

### ISSUE THREAD

**Issue by WillemUXMendix** [mendix/AppStoreWidgetBoilerplate#17]
The current boilerplate uses the js "forEach" function in the resetHandlers() function.
However, this is not supported by IE8. 

Easily fixed by replacing it with Dojo's Array forEach functionality.
However, the js part of the boilerplate should be analysed to see if there are any other IE8 non compatible elements.

**Comment by Andries-Smit** [comment]
Fix by Roelands branch was not pulled to the mainline.

**Comment by JelteMX** [comment]
Fixed in next release
