### ISSUE TITLE
jquery min file is missing

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/AppStoreWidgetBoilerplate#24]
at https://github.com/mendix/AppStoreWidgetBoilerplate/blob/master/src/WidgetName/widget/WidgetName.js#L34

is referred to minified jquery library, how ever this on is not available. Suggested change:
https://github.com/mendix/AppStoreWidgetBoilerplate/pull/23

Kind regards, Andries

**Comment by JelteMX** [comment]
Will create a new release today
