### ISSUE TITLE
Alert Div is Placed Incorrectly

### ISSUE THREAD

**Issue by chadevans** [mendix/AppStoreWidgetBoilerplate#26]
When creating a widget that needs to respond to a validation message, the default code is incorrect. This line in _showError()

dojoConstruct.place(this.domNode, this._alertdiv);

Has the parameters reversed, causing the node to disappear. The line should be:

dojoConstruct.place(this._alertdiv, this.domNode);

**Comment by Andries-Smit** [comment]
Fixed in pull request #32

**Comment by JelteMX** [comment]
Fix will be included in the next release today
