### ISSUE TITLE
Decimal is not possible as an element type

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/AppStoreWidgetBoilerplate#42]
A decimal value is possible if it's an attribute, but not as a propertyType 'type'

 Widget XML file '' does not conform to the XML schema:
Het kenmerk type is ongeldig. De waarde decimal is ongeldig volgens het bijbehorende gegevenstype http://www.mendix.com/widget/1.0/:propertyTypeType - De Enumeration-beperking is mislukt.

**Comment by JelteMX** [comment]
Long overdue. I checked this with R&D. I have updated the XSD. The property type is set here:

```xml
 <property key="{{key in the widget}}" type="{{property type}}">
```

It is indeed not possible to set a decimal. If you want to use a decimal in the Modeler right now, you will have to set this as a string and do a ``parseFloat(key)`` in the widget. Unfortunately this is not something that I have influence to. I suggest you add a request to [the Idea Forum](https://forum.mendixcloud.com/index3.html) for this.

I am closing this issue, as the AppStoreWidgetBoilerplate is not maintained by R&D, but Community
