### ISSUE TITLE
Unable to use dashes ( '-' ) in enumerationKey 

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/AppStoreWidgetBoilerplate#44]
I can't use dashes ( '-') in an enumeration key attribute. Why is that and can that be added.

For example:

`<enumerationValue key="key-with-dash">Key</enumerationValue>` is invalid.

**Comment by JelteMX** [comment]
Unfortunately, that's just the way it is. It should be possible to use underscores (``_``) though. This is a limitation of the Modeler and widget.xml and is not really an issue with the boilerplate.

**Comment by RoelandSalij** [comment]
But I do guess there is a reason for it, but please post your question on the forum or file a ticket in the support portal as the guys working on this part of the platform can answer this question.

**Comment by Mcpoowl** [comment]
Thanks guys I'll do that. 
@JelteMX I noticed, and after I posted this I immediatly thought it probably wasn't disabled as a choice. The reason I was asking is my enumeration key is directly linked to a class element I try to map to a domNode. Being able to use the hypened class-name would save me a lot of String manipulation hassle :-)

**Comment by JelteMX** [comment]
I know and understand. Have encountered this limitation myself as well in other widgets. Allthoug a simple ```key.replace(/_/g,'-')```will fix it for you. My thoughts (have seen the forum post, not any answers) is that's it's a limitation of parsing XML in the Modeler (I have seen the source-code, will ask R&D the same question as well, now I'm curious)

**Comment by Mcpoowl** [comment]
Thanks @JelteMX , keep me posted!
