### ISSUE TITLE
Use of undocumented Mendix API

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/AppStoreWidgetBoilerplate#45]
Dear Mendix,

The API Documentation does not describe the use of the nullExec function of the boilerplate
https://github.com/mendix/AppStoreWidgetBoilerplate/blob/master/src/WidgetName/widget/WidgetName.js#L180

```
// The callback, coming from update, needs to be executed, to let the page know it finished rendering
mendix.lang.nullExec(callback);
```

It should be updated in the documentation https://apidocs.mendix.com/6/client/module-mendix_lang.html

We have also noted that the code is:

```
mendix.lang.nullExec = function(callback) {
        callback && callback();
};
```

This bit of code is tries to execute a parameter even if it is not of the type function. It would be better to check if for it.

```
mendix.lang.nullExec = function(callback) {
     if (typeof callback === "function") {
           callback();
     } else {
          console.warn("nullExec should have a function as argument")
     }
};
```

**Comment by JelteMX** [comment]
This is [removed](https://github.com/mendix/AppStoreWidgetBoilerplate/commit/19b3e8d5a8219237d180a1d9cd1645604a223fc9), because it will be considered (still works) deprecated in Mendix 7. The use of undocumented APIs is strongly discouraged.
