### ISSUE TITLE
Test project does not compile in Mendix 6.7.1

### ISSUE THREAD

**Issue by markroemers** [mendix/AppStoreWidgetBoilerplate#46]
L.S.

Just downloaded this project and tried to run it in Mendix 6.7.1.
There are no errors reported in Mendix but I do get Java compile errors.

[java_compile_errors.txt](https://github.com/mendix/AppStoreWidgetBoilerplate/files/442110/java_compile_errors.txt)

Please advise,

Mark

**Comment by hgeldenhuys** [comment]
This is a GoogleCharts product bug and not an AppStoreWidgetBoilerplate issue. 

Your bug is Java code, but ASWB is only javascript. You probably did a Mendix upgrade to 6.x and need to read the the [Release notes and search for getDTAPMode](https://world.mendix.com/display/ReleaseNotes/6.0.0)

I suggest you go to [GoogleCharts](https://github.com/mrgroen/GoogleCharts)

**Comment by JelteMX** [comment]
As @hgeldenhuys says, this is GoogleCharts. Closing this one, please file a ticket at the appropriate repository

**Comment by RoelandSalij** [comment]
I've read the stacktrace and I do suspect the RestServices module needs to be upgraded in that project.
You can update your instance of this project by downloading the RestService module using the App Store.

**Comment by markroemers** [comment]
Thanks!


Regards

Mark Roemers

Email:   mark.roemers@anttail.com<mailto:mark.roemers@anttail.com>
Phone: +31629001555
Web: http://www.AntTail.com

Address:  Nieuwegracht 32, 3512 LS Utrecht, The Netherlands

AntTail designs, develops and delivers products and services to monitor and track the origin and temperature of medicines throughout the cold chain. AntTail cloud computing and SaaS based solutions help to ensure product quality and prevent counterfeiting. Pharmaceutical, transportation and logistic service providers, healthcare providers and retail outlets can follow shipments and deliveries, checking temperature every step of the way. AntTail works within existing  cold chain quality procedures, eliminating the need for complex implementation and capital investments.

On 30 Aug 2016, at 09:46, Roeland Salij <notifications@github.com<mailto:notifications@github.com>> wrote:


I've read the stacktrace and I do suspect the RestServices module needs to be upgraded in that project.
You can update your instance of this project by downloading the RestService module using the App Store.
