### ISSUE TITLE
Return typing contains deprecated float type

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/AppStoreWidgetBoilerplate#48]
Float is not used anymore, but the typing is still in. And the Decimal type is missing
https://github.com/mendix/AppStoreWidgetBoilerplate/blob/master/xsd/widget.xsd#L133

**Comment by JelteMX** [comment]
Fixed here [https://github.com/mendix/AppStoreWidgetBoilerplate/commit/34f11bd5cb981d8d10f1f07d7ef50f2e7b72beef}, will update widget generator and create a new release here
