### ISSUE TITLE
What does the store parameter do?

### ISSUE THREAD

**Issue by Narev** [mendix/AppStoreWidgetBoilerplate#52]
The template uses a mx.data.action call in which it adds a store parameter. What does it do exactly as the documentation does not mention the parameter.

` 

                        mx.data.action({params: {
                            applyto: "selection",
                            actionname: this.mfToExecute,
                            guids: [ this._contextObj.getGuid() ]
                        },
                        store: {
                            caller: this.mxform
                        },
                        callback: function (obj) {
                            //TODO what to do when all is ok!
                        },
                        error: dojoLang.hitch(this, function (error) {
                            logger.error(this.id + ": An error occurred while executing microflow: " + error.description);
                        })
                    }, this);`

**Comment by JelteMX** [comment]
This has to do with the form it was submitted from, which is not documented indeed. I will refactor this, because it shouldn't be used anymore (in Mendix 7 it's deprecated)

**Comment by JelteMX** [comment]
Fixed in [74eea5](https://github.com/mendix/AppStoreWidgetBoilerplate/commit/74eea5f3bc7ab878f8d37a1fad9056977effb708)
