### ISSUE TITLE
why is mendix version still on 5.x migrate to latest please.

### ISSUE THREAD

**Issue by vasanramani** [mendix/AppStoreWidgetBoilerplate#59]

**Comment by JelteMX** [comment]
This boilerplate is supported by Mendix 5 up to the latest version. Our test-projects vary in which version it is built, but it should support Mendix 5. This is part of our SLA.

When Mendix 8 is released eventually, the minimum supported version will be Mendix 6.

I am closing this issue

**Comment by vasanramani** [comment]
Thanks.
