### ISSUE TITLE
Use of double quotes not single quotes

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/AppStoreWidgetBoilerplate#7]
There are are a lot of discussion if you one should use single or double quotes for strings in javascript. Though both are technically the same, Mendix (mxui), json, html and dojo uses double quotes as their standard.

This boilerplate uses all single quotes. 
Should we convert them?

(a double whiskey is better the a single : )

**Comment by johanflint** [comment]
Inside R&D we use double quotes everywhere and we recommend custom widget writers to do the same in order to be consistent.
