### ISSUE TITLE
use of space and tabs

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/AppStoreWidgetBoilerplate#8]
The outlining of the code is getting a bit messy due to mixed use of tab and space.
https://github.com/mendix/AppStoreWidgetBoilerplate/blob/master/src/WidgetName/widget/WidgetName.js

Please give guide to other users to use one of them. 
Is there any code formatting standard that is used within Mendix dev team?

Thanks

**Comment by johanflint** [comment]
Good question. At R&D we use 4 spaces for indentation in our JS code. We also use double quotes instead of single quotes.

We will fix the inconsistencies in the boilerplate as soon as we have some time for it.
