### ISSUE TITLE
Documentation needs an update

### ISSUE THREAD

**Issue by RCatersels** [mendix/AppStoreWidgetBoilerplate#9]
From 6.1 onwards in the documentation they refer to Entity_Test_NewEdit but this entity is no longer part of the TestSuite Module. New screenshots should be added to the documentation here: https://world.mendix.com/display/howto50/Getting+started+with+the+Widget+Development+Plugin+for+Adobe+Brackets

Regards,

Ronald

**Comment by GREdens** [comment]
Thank you for your input! We are working on this as we speak.  :+1:  Actually the documentation will be split where a new how-to will be written that goes in depth view on the new Mendix test application. The new Mendix test application contains allot of scenarios that you need to cover when developing new widgets.
